server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/chatty_db  # Ensure the correct database name
    username: chatty                           # Use the correct database username
    password: ChattyApp                        # Use the correct database password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: "your_generated_secret_key_here"  # Replace with a strong key

management:
  endpoints:
    web:
      exposure:
        include: "*"